language: objective-c
osx_image: beta-xcode6.3
env:
  global:
  - LANG=en_US.UTF-8
install:
- bundle install --jobs=3 --retry=3
- bundle exec pod install
script:
- bundle exec rake lint
- bundle exec rake test
